### ISSUE TITLE
GBM_WSSM.h5 link broken

### ISSUE THREAD

**Issue by simonpcastillo** [amin20/GBM_WSSM#3]
Hi, the link to GBM_WSSM.h5 is broken. Please, can you check it?

**Comment by amin20** [comment]
> Hi, the link to GBM_WSSM.h5 is broken. Please, can you check it?

Hello,

I just checked the link and it works properly. 
Change your browser, please and check again.

Thanks,

**Comment by jeanrclemenceau** [comment]
Hello, it looks like the link to [GBM_WSSM.h5](https://1drv.ms/u/s!AvQTr_2MktoOgQT_ZMbotiquQW0L?e=ehFJah) is broken again. Can you please update it? 

By the way, I checked on Firefox, Chrome, Edge, and even Internet Explorer.
