### ISSUE TITLE
Handle class Class_Augmentation.Augmentation

### ISSUE THREAD

**Issue by simonpcastillo** [amin20/GBM_WSSM#4]
Running the code `0_main.py` I got this error when running line 232:

`ValueError: Failed to find data adapter that can handle input: <class 'Class_Augmentation.Augmentation'>, <class 'NoneType'>`

keras 2.4.3 -  tensorflow 2.3.0

**Comment by amin20** [comment]
The code is telling you: 
**"Failed to find data adapter that can handle input"**

Check your data entry/NumPy arrays/images as inputs.
